name: aarch64-linux-musl-ubuntu-24.04

on:
  push:
    tags: [ 'v*' ]

env:
  IMAGE_NAME: bitshock/aarch64-linux-musl-ubuntu-24.04

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tags and labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          file: ubuntu.Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            TARGET=aarch64-linux-musl
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
